# Generated by Django 5.0.6 on 2026-09-16 14:55

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('core', '0002_alter_notification_notification_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('None', 'None'), ('Transfer', 'Transfer'), ('Credit Alert', 'Credit Alert'), ('Debit Alert', 'Debit Alert'), ('Sent Payment Request', 'Sent Payment Request'), ('Recieved Payment Request', 'Recieved Payment Request'), ('Funded Credit Card', 'Funded Credit Card'), ('Withdrew Credit Card Funds', 'Withdrew Credit Card Funds'), ('Deleted Credit Card', 'Deleted Credit Card'), ('Added Credit Card', 'Added Credit Card'), ('Withdrawal Requested', 'Withdrawal Requested'), ('Withdrawal Completed', 'Withdrawal Completed'), ('Withdrawal Cancelled', 'Withdrawal Cancelled'), ('Cash Received', 'Cash Received'), ('Service Payment', 'Service Payment'), ('Service Fee', 'Service Fee'), ('Payment Received', 'Payment Received')], default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('recieved', 'Recieved'), ('withdraw', 'withdraw'), ('refund', 'Refund'), ('request', 'Payment Request'), ('payment', 'Service Payment'), ('fee', 'Service Fee'), ('none', 'None')], default='none', max_length=100),
        ),
        migrations.CreateModel(
            name='ServicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=20, prefix='PAY', unique=True)),
                ('service', models.CharField(choices=[('agharina', 'Paiement Agharina')], default='agharina', max_length=40)),
                ('reference', models.CharField(max_length=120)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('type_bien', models.CharField(blank=True, max_length=60)),
                ('type_transaction', models.CharField(blank=True, max_length=60)),
                ('unite_prix', models.CharField(blank=True, max_length=40)),
                ('snapshot', models.JSONField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0.02, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Paye'), ('failed', 'Echoue')], default='pending', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_payments', to='account.account')),
                ('tax_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_payment_tax', to='core.transaction')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_payment', to='core.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Payment',
                'verbose_name_plural': 'Service Payments',
                'ordering': ['-date'],
            },
        ),
    ]
