"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ---------------------------------------------------------------------------
# Configuration pilotee par l'environnement (dev local vs Render)
# ---------------------------------------------------------------------------
def env_bool(name, default=False):
    return os.environ.get(name, str(default)).strip().lower() in ("1", "true", "yes", "on")


def env_list(name, default=""):
    return [item.strip() for item in os.environ.get(name, default).split(",") if item.strip()]


# SECURITY WARNING: en production, DJANGO_SECRET_KEY est obligatoire.
# La valeur de repli ne sert qu'au developpement local.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-dev-only--$v7_sq7)6y#1)uv-hchc5s)d5hm=*oygs(-%k9a2dzm$qma6f",
)

# DEBUG est desactive par defaut : il faut le demander explicitement en local.
DEBUG = env_bool("DJANGO_DEBUG", True if os.environ.get("RENDER") is None else False)

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,.onrender.com")

# Ancien site HTML (accueil marketing, connexion, tableau de bord Django).
# Actif en developpement, eteint en production : sur un domaine sans reputation,
# une page d'accueil de banque en ligne avec formulaires de mot de passe et de
# carte bancaire declenche les filtres anti-hameconnage des navigateurs.
# L'interface client est le frontend React.
SERVE_LEGACY_SITE = env_bool("SERVE_LEGACY_SITE", DEBUG)

# Render expose le hostname public du service dans cette variable.
RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

if DEBUG:
    ALLOWED_HOSTS.append("*")


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django_extensions',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
     # Custom Apps
    'core',
    'userauths',
    'account',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',  # new
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'

AUTH_USER_MODEL = 'userauths.User'
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# En local : SQLite. Sur Render : la variable DATABASE_URL du service Postgres.
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        ssl_require=bool(os.environ.get("DATABASE_URL")) and not DEBUG,
    )
}


# DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql',
#        'NAME': 'digitalbanking',
#        'USER': 'postgres',
#        'PASSWORD': '46981937',
#        'HOST': 'localhost',
#        'PORT': '5432'
#    }
# }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Sans l'ancien site, la page de connexion HTML n'existe plus : on renvoie
# vers l'administration pour que reverse() reste valide.
if SERVE_LEGACY_SITE:
    LOGIN_URL = "userauths:sign-in"
    LOGOUT_REDIRECT_URL = "userauths:sign-in"
else:
    LOGIN_URL = "/admin/login/"
    LOGOUT_REDIRECT_URL = "/admin/login/"

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Django 5 : la configuration des stockages passe par STORAGES.
# Le backend statique tolere les references cassees (voir project/storage.py).
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "project.storage.ForgivingManifestStaticFilesStorage",
    },
}

# STATIC_URL = '/static/'
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'assets')]
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ---------------------------------------------------------------------------
# Durcissement applique uniquement hors DEBUG (donc en production)
# ---------------------------------------------------------------------------
if not DEBUG:
    # Render termine le TLS en amont : sans cet en-tete Django croit etre en HTTP.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"



# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES':(
        'rest_framework.permissions.IsAuthenticated',
    ),

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',# new
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Blog API Project",
    "DESCRIPTION": "A sample blog to learn about DRF",
    "VERSION": "1.0.0",
    # OTHER SETTINGS
}



# digitalbanking

AUTH_USER_MODEL = 'userauths.User'

# JAZZMIN_SETTINGS = {
#     # "site_title": "MovieX",
#     "site_header": "PoolPay",
#     "site_title":"PoolPay",
#     "site_brand": "Payment Made Easy...",
#     "site_logo": "assets/images/logo.png",
#     "copyright": "PoolPay - All RIght Reserverd © Copyright 2024",
#     # "order_with_respect_to": ["core", 'userauths', "transactions" , 'addon', 'blog']

    
# }


# Dans settings.py

JAZZMIN_SETTINGS = {
    "site_title": "PoolPay",
    "site_header": "PoolPay",
    "site_brand": "Payment Made Easy...",
    "site_logo": "assets/images/logo.png",
    "login_logo": None,
    "login_logo_dark": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    "welcome_sign": "Bienvenue dans l'administration PoolPay",
    "copyright": "PoolPay - All Rights Reserved © Copyright 2024",
    "search_model": ["auth.User", "core.Transaction"],
    
    # Personnalisation de l'interface utilisateur
    "topmenu_links": [
        {"name": "Accueil", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Site Web", "url": "/", "new_window": True},
        {"model": "auth.User"},
        {"app": "core"},
        {"app": "account"},
    ],
    
    # Tableau de bord personnalisé
    "show_ui_builder": True,
    
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible", 
        "auth.group": "vertical_tabs"
    },
    
    # Icônes personnalisées
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "core.Transaction": "fas fa-money-bill-wave",
        "core.CreditCard": "fas fa-credit-card",
        "core.Notification": "fas fa-bell",
        "account.Account": "fas fa-wallet",
        "account.KYC": "fas fa-id-card",
        "userauths.User": "fas fa-users",
    },
    
    # Menu personnalisé
    "order_with_respect_to": ["core", "account", "userauths"],
    
    "custom_links": {
        "core": [{
            "name": "Statistiques", 
            "url": "admin_stats", 
            "icon": "fas fa-chart-line",
            "permissions": ["core.view_transaction"]
        }]
    },
    
    # Thème et couleurs
    "theme": "default",
    "dark_mode_theme": None,
    
    "related_modal_active": False,
    "use_google_fonts_cdn": True,
    "show_ui_builder": True,
    
    "custom_css": "css/admin_custom.css",
    "custom_js": "js/admin_custom.js",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
# JAZZMIN_UI_TWEAKS = {
#     "navbar_small_text": False,
#     "footer_small_text": False,
#     "body_small_text": True,
#     "brand_small_text": False,
#     "brand_colour": "navbar-indigo",
#     "accent": "accent-olive",
#     "navbar": "navbar-indigo navbar-dark",
#     "no_navbar_border": False,
#     "navbar_fixed": False,
#     "layout_boxed": False,
#     "footer_fixed": False,
#     "sidebar_fixed": False,
#     "sidebar": "sidebar-dark-indigo",
#     "sidebar_nav_small_text": False,
#     "sidebar_disable_expand": False,
#     "sidebar_nav_child_indent": False,
#     "sidebar_nav_compact_style": False,
#     "sidebar_nav_legacy_style": False,
#     "sidebar_nav_flat_style": False,
#     "theme": "cyborg",
#     "dark_mode_theme": "cyborg",
#     "button_classes": {
#         "primary": "btn-primary",
#         "secondary": "btn-secondary",
#         "info": "btn-info",
#         "warning": "btn-warning",
#         "danger": "btn-danger",
#         "success": "btn-success"
#     }
# }



SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# ---------------------------------------------------------------------------
# CORS : autorise le frontend React (Vite) a appeler l'API depuis un autre port
# ---------------------------------------------------------------------------
# Origines autorisees : les fronts locaux + celles fournies par l'environnement
# (ex. CORS_ALLOWED_ORIGINS="https://poolpay.onrender.com,https://app.exemple.com").
CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS",
    # Fronts locaux : indispensables car .env pointe vers le backend deploye,
    # donc "npm run dev" appelle la production depuis localhost.
    "http://localhost:5173,http://127.0.0.1:5173,"
    "http://localhost:4173,http://127.0.0.1:4173,"
    # Frontend en ligne.
    "https://frontend-digital-banking.vercel.app",
)
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = env_list(
    "CSRF_TRUSTED_ORIGINS",
    "http://localhost:5173,http://127.0.0.1:5173,"
    "https://frontend-digital-banking.vercel.app",
) + ["https://*.onrender.com"]

if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f"https://{RENDER_EXTERNAL_HOSTNAME}")

# En developpement, Vite peut basculer sur un autre port (5174, 5175...) :
# on autorise donc n'importe quel port local.
# Motifs d'origines autorisees, en plus de la liste exacte ci-dessus.
# Utile pour les deploiements de previsualisation Vercel, dont l'URL change a
# chaque commit. Exemple, en restreignant bien a VOTRE projet :
#   CORS_ALLOWED_ORIGIN_REGEXES="^https://poolpay-.*[.]vercel[.]app$"
# Par defaut : les deploiements de previsualisation de CE projet Vercel,
# dont l'URL change a chaque commit. Restreint au prefixe du projet.
CORS_ALLOWED_ORIGIN_REGEXES = env_list(
    "CORS_ALLOWED_ORIGIN_REGEXES",
    r"^https://frontend-digital-banking-.*[.]vercel[.]app$",
)

if DEBUG:
    # En local, Vite peut basculer sur un autre port (5174, 5175...).
    CORS_ALLOWED_ORIGIN_REGEXES += [
        r"^http://localhost:[0-9]+$",
        r"^http://127[.]0[.]0[.]1:[0-9]+$",
    ]

# ---------------------------------------------------------------------------
# Service "Paiement Agharina" (immobilier)
# ---------------------------------------------------------------------------
# API publique qui decrit les biens ; le backend la reinterroge lui-meme au
# moment du paiement pour ne jamais faire confiance au prix envoye par le client.
AGHARINA_API_URL = os.environ.get("AGHARINA_API_URL", "https://admin-akarina.akarina.shop/api/biens")
AGHARINA_API_TIMEOUT = 20

# Comptes de service PoolPay (modifiables : ce sont de vrais comptes clients).
# - AGHARINA : recoit le montant du bien
# - BANK     : recoit la taxe de service
AGHARINA_ACCOUNT_NUMBER = os.environ.get("AGHARINA_ACCOUNT_NUMBER", "2172328718882")
POOLPAY_BANK_ACCOUNT_NUMBER = os.environ.get("POOLPAY_BANK_ACCOUNT_NUMBER", "2171123705801")

# Taxe de service prelevee en plus du prix du bien (2 %).
SERVICE_TAX_RATE = os.environ.get("SERVICE_TAX_RATE", "0.02")
